# Cloud Build configuration for Stonepot Restaurant
# Automates Docker image building and Cloud Run deployment

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/stonepot-restaurant:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/stonepot-restaurant:latest'
      - '.'
    id: 'build-image'

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/stonepot-restaurant:$COMMIT_SHA'
    id: 'push-image-sha'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/stonepot-restaurant:latest'
    id: 'push-image-latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'stonepot-restaurant'
      - '--image=gcr.io/$PROJECT_ID/stonepot-restaurant:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=300'
      - '--concurrency=80'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production,ENVIRONMENT=production,CLOUDFLARE_WORKER_URL=https://theme-edge-worker.suyesh.workers.dev'
    id: 'deploy-cloud-run'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/stonepot-restaurant:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/stonepot-restaurant:latest'

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
